# Generated by Django 4.1 on 2024-10-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/img1.jpg', upload_to='thumbnails/'),
        ),
    ]
